### ISSUE TITLE
manim Studio does not start on Mac OS with python 3.1

### ISSUE THREAD

**Issue by gro1729** [MathItYT/manim-studio#19]
**a call of manim-studio results in**
~/Downloads/manim % manim-studio --version                                   (master)manim
Manim Community v0.18.0

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/manim-studio", line 5, in <module>
    from manim_studio.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim_studio/__main__.py", line 2, in <module>
    from manim_studio.editor_widget import EditorWidget
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim_studio/editor_widget.py", line 30, in <module>
    from manim_studio.mobject_picker import MobjectPicker, RefreshDropdownVGroupButton
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim_studio/mobject_picker.py", line 311
    f"setattr(self, {name.__repr__()}, MathTex({"\\ln x=\\int_1^x{dt\\over t}".__repr__()}))")
                                                  ^
SyntaxError: unexpected character after line continuation character

**Comment by MathItYT** [comment]
Yea, it's something that I've noticed. The latest version only supports Python 3.12, where it works correctly.

**Comment by gro1729** [comment]
Thats a good hint. But unfortunately, it does not seem to work. 

manim-studio is successfully installed via:

pip3.12 install manim-studio --break-system-packages

but

python3.12 -m manim-studio 

results in:

/opt/homebrew/opt/python@3.12/bin/python3.12: No module named manim-studio

**Comment by MathItYT** [comment]
The module is manim_studio, not manim-studio.

**Comment by MathItYT** [comment]
`python3.12 -m manim_studio`

**Comment by gro1729** [comment]
Thanks a lot for your hint. Sorry, there is still another problem remaining. I am not an experienced Python developer.


~/Downloads/manim % python3.12 -m manim_studio
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      python3.12 -m manim_studio

**Comment by MathItYT** [comment]
Sorry for late response. Try running `pip install opencv-python`. If that doesn't work, tell me.

**Comment by gro1729** [comment]
I tried:

python3.12 -m pip install opencv-python --break-system-packages
DEPRECATION: Loading egg at /opt/homebrew/Cellar/gpgme/1.23.2/lib/python3.12/site-packages/gpg-1.23.2-py3.12-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.12/site-packages (4.9.0.80)
Requirement already satisfied: numpy>=1.21.2 in /opt/homebrew/lib/python3.12/site-packages (from opencv-python) (1.26.3)

and as well
pip3.12 install opencv-python --break-system-packages
DEPRECATION: Loading egg at /opt/homebrew/Cellar/gpgme/1.23.2/lib/python3.12/site-packages/gpg-1.23.2-py3.12-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.12/site-packages (4.9.0.80)
Requirement already satisfied: numpy>=1.21.2 in /opt/homebrew/lib/python3.12/site-packages (from opencv-python) (1.26.3)

which again results in:
>python3.12 -m manim_studio                               (master)manim
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      python3.12 -m manim_studio

**Comment by gro1729** [comment]
> I tried:
> 
> python3.12 -m pip install opencv-python --break-system-packages DEPRECATION: Loading egg at /opt/homebrew/Cellar/gpgme/1.23.2/lib/python3.12/site-packages/gpg-1.23.2-py3.12-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.12/site-packages (4.9.0.80) Requirement already satisfied: numpy>=1.21.2 in /opt/homebrew/lib/python3.12/site-packages (from opencv-python) (1.26.3)
> 
> and as well pip3.12 install opencv-python --break-system-packages DEPRECATION: Loading egg at /opt/homebrew/Cellar/gpgme/1.23.2/lib/python3.12/site-packages/gpg-1.23.2-py3.12-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at [pypa/pip#12330](https://github.com/pypa/pip/issues/12330) Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.12/site-packages (4.9.0.80) Requirement already satisfied: numpy>=1.21.2 in /opt/homebrew/lib/python3.12/site-packages (from opencv-python) (1.26.3)
> 
> which again results in:
> 
> > python3.12 -m manim_studio                               (master)manim
> > qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
> > This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> zsh: abort python3.12 -m manim_studio

Are there any ideas how to get manim-studio get running?

**Comment by gro1729** [comment]
Meanwhile I found, that it seems to be necessary to define an environment variable:
My setting is:
export QT_QPA_PLATFORM_PLUGIN_PATH=/opt/homebrew/Cellar/qt/6.6.2/share/qt/plugins/platforms
Now manim-studio seems to start.
